//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AgentCard
    {
        public int Id { get; set; }
        public int CardId { get; set; }
        public int AgentId { get; set; }
        public decimal Cost { get; set; }

        public decimal PriceAgent { get; set; }
        //public Nullable<decimal> PriceReseller { get; set; }
        public  decimal  PriceCustomer { get; set; }
        //public Nullable<bool> IsUpdated { get; set; }
        public  bool  IsActive { get; set; }
        //public Nullable<decimal> CurrentPrice { get; set; }
        //public Nullable<decimal> PriceCustomerOffer { get; set; }
        //public Nullable<decimal> PriceAgentOffer { get; set; }
        //public Nullable<decimal> PriceCostOffer { get; set; }

        [ForeignKey("AgentId")]
        [InverseProperty("AgentCards")]
        public virtual Agent Agent { get; set; }

        [ForeignKey("CardId")]
        [InverseProperty("AgentCards")] 
        public virtual Card Card { get; set; }
    }
}
