//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            //this.DealerBills = new HashSet<DealerBill>();
            //this.DealerBills1 = new HashSet<DealerBill>();
            //this.DealerInvoices = new HashSet<DealerInvoice>();
            //this.DelearsAdvertys = new HashSet<DelearsAdverty>();
            //this.SubscriptionBills = new HashSet<SubscriptionBill>();
            //this.SubscriptionPrices = new HashSet<SubscriptionPrice>();
            //this.Subscriptions = new HashSet<Subscription>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string? City { get; set; }
        public Nullable<int> ParentAgentId { get; set; }
        public string UserId { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public bool AllowSub { get; set; }
        public bool IsDeleted { get; set; }
        public bool AllowLoan { get; set; }
        public  string? Address { get; set; }
        public string?  Phone { get; set; }
        public string Mobile { get; set; }

        [ForeignKey("UserId")]
        //[InverseProperty("")]
        public virtual ApplicationUser ApplicationUser { get; set; }

        [ForeignKey("ParentAgentId")]
        [InverseProperty("Agents")]
        public virtual Agent ParentAgent { get; set; }

        public virtual ICollection<Agent> Agents { get; set; }
        public virtual ICollection<AgentCard> AgentCards { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }












        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerBill> DealerBills { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerInvoice> DealerInvoices { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DelearsAdverty> DelearsAdvertys { get; set; }




        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionBill> SubscriptionBills { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionPrice> SubscriptionPrices { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }



    }
}
