//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APILog
    {
        public int Id { get; set; }
        public string API { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UserId { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
    
        public virtual Category Company { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
