//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealerInvoice()
        {
            this.DealerBills = new HashSet<DealerBill>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<decimal> PreviousCredit { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<int> Old_Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> DealerToId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerBill> DealerBills { get; set; }
        public virtual Agent Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
    }
}
