//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoicePayment()
        {
            //this.Payments = new HashSet<Payments>();
            this.PaymentsTaxes = new HashSet<PaymentsTax>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> TaxType { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DealerNumber { get; set; }
        public Nullable<int> RelatedPayments { get; set; }
    
        public virtual DealerInvoice DealerInvoice { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentsTax> PaymentsTaxes { get; set; }
    }
}
