//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Seen { get; set; }
        public string Type { get; set; }
        public string TextAr { get; set; }
        public string TextEn { get; set; }
        public string Text { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}
