//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagesCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackagesCompany()
        {
            this.PackagesCompaniesDealers = new HashSet<PackagesCompaniesDealer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string GB { get; set; }
        public string Cost { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Prepaid { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceOffer { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<bool> CanCutDuringOffer { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> SMS { get; set; }
        public string Note { get; set; }
    
        public virtual Category Company { get; set; }
        public virtual PackageOffer PackageOffer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackagesCompaniesDealer> PackagesCompaniesDealers { get; set; }
    }
}
