//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagesCompaniesDealer
    {
        public int Id { get; set; }
        public Nullable<int> PackagesCompaniesId { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> PriceCostOffer { get; set; }
    
        public virtual Agent Distributor { get; set; }
        public virtual PackagesCompany PackagesCompany { get; set; }
    }
}
