//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LiveCards.Models;

public partial class Payment
{

    public int Id { get; set; }
    [DisplayFormat(DataFormatString = "{dd/MM/yyyy}")]
    public DateTime Date { get; set; }
    public decimal Amount { get; set; }
    public decimal ExhangeRate { get; set; }
    public string Note { get; set; }
    public int Status { get; set; }
    public bool IsDelete { get; set; }
    public int AgentId { get; set; }

    [ForeignKey("AgentId")]
    public Agent Agent { get; set; }



    //public int Id { get; set; }
    //public Nullable<int> InvoicePaymentId { get; set; }
    //public Nullable<int> PaymentType { get; set; }
    //public Nullable<decimal> Amount { get; set; }
    //public Nullable<System.DateTime> Date { get; set; }
    //public string Note { get; set; }
    //public string CeditCardJson { get; set; }
    //public string CheckJson { get; set; }

    //public virtual InvoicePayment InvoicePayment { get; set; }
}
