//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsTax
    {
        public int Id { get; set; }
        public Nullable<int> InvoicePaymentId { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string SKU { get; set; }
        public string Details { get; set; }
    
        public virtual InvoicePayment InvoicePayment { get; set; }
    }
}
