//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permission()
        {
            //this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public int Id { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Icon { get; set; }
        public string CurrentPage { get; set; }
        public string Description { get; set; }
        public string DescriptionEn { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
