//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.APILogs = new HashSet<APILog>();
            this.Comments = new HashSet<Comment>();
            this.DealerBills = new HashSet<DealerBill>();
            this.SubscriptionBills = new HashSet<SubscriptionBill>();
            this.SubscriptionPrices = new HashSet<SubscriptionPrice>();
            this.Tickets = new HashSet<Ticket>();
            this.UploadedFiles = new HashSet<UploadedFile>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<int> NumberId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> GB { get; set; }
        public Nullable<System.DateTime> ConnectionDate { get; set; }
        public Nullable<System.DateTime> CutDate { get; set; }
        public string SIMNumber { get; set; }
        public string SIMCar { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> OpenService { get; set; }
        public Nullable<bool> AutomaticRenewal { get; set; }
        public string RenewPackage { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> SIMCarPrice { get; set; }
        public Nullable<int> OldCompanyId { get; set; }
        public string OldNumber { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SimStatus { get; set; }
        public Nullable<bool> IsOffer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APILog> APILogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        //public virtual Company Company { get; set; }
        //public virtual Company Company1 { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealerBill> DealerBills { get; set; }
        public virtual Agent Distributor { get; set; }
        public virtual Number Number { get; set; }
        public virtual Card Card { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionBill> SubscriptionBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionPrice> SubscriptionPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedFile> UploadedFiles { get; set; }
    }
}
