//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketNote
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Note { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
        public Nullable<int> TicketId { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
