//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveCards.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketNotes = new HashSet<TicketNote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Beneficiary { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string TextAr { get; set; }
        public string TextEn { get; set; }
        public string Text { get; set; }
        public string Data { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DatePerformed { get; set; }
        public string SIM { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketNote> TicketNotes { get; set; }
        public virtual TicketTopic TicketTopic { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
